15_rails/nightclub/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :performers

  #resources (adds index, show, new, create, edit, update, delete)


end

15_rails/nightclub/app/models/performer.rb
class Performer < ApplicationRecord
end

15_rails/nightclub/app/controllers/performers_controller.rb
class PerformersController < ApplicationController

  def index
    @performers = Performer.all
  end

  def show #/performers/:id
    @performer = Performer.find(params[:id])
  end

  def new
    @performer = Performer.new
  end

  def create
    @performer = Performer.create(name: params[:performer][:name])
    redirect_to @performer
  end

  def edit #/performers/:id
    @performer = Performer.find(params[:id])
  end

  def update
    @performer = Performer.find(params[:id])
    @performer.update(name: params[:performer][:name])

    redirect_to @performer
  end

  # def delete
  #   byebug
  #   @performer = Performer.find(params[:id])
  #   @performer.destroy
  #
  #   redirect_to performers_path
  # end

  def destroy
    @performer = Performer.find(params[:id])
    @performer.destroy

    redirect_to performers_path
  end
end

15_rails/nightclub/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nightclub</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

15_rails/nightclub/app/views/performers/edit.html.erb
<%= form_for @performer do |f| %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

<%= form_tag(performer_path(@performer), method: "delete") do  %>
  <%= submit_tag "Delete Performer"  %>
<% end %>

15_rails/nightclub/app/views/performers/index.html.erb
<ul>
  <% @performers.each do |p| %>
    <li><%= p.name  %></li>
  <% end %>
</ul>

15_rails/nightclub/app/views/performers/new.html.erb
<%= form_for @performer do |f| %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

15_rails/nightclub/app/views/performers/show.html.erb
<%= @performer.name %>