20_rails_auth/lastam/config/routes.rb
Rails.application.routes.draw do
  resources :songs
  resources :users, only: [:create, :show]
  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  post "sessions", to: "sessions#create", as: "sessions"
  delete "sessions", to: "sessions#destroy"

end

20_rails_auth/lastam/app/models/song.rb
class Song < ApplicationRecord
  has_many :user_songs
  has_many :users, through: :user_songs
end

20_rails_auth/lastam/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :user_songs
  has_many :songs, through: :user_songs
end

20_rails_auth/lastam/app/models/user_song.rb
class UserSong < ApplicationRecord
  belongs_to :user
  belongs_to :song
end

20_rails_auth/lastam/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authorized
  helper_method :logged_in?


  def current_user
    if session[:user_id]
      @user = User.find_by(id: session[:user_id])
    else
    end
  end


  def logged_in?
    !!current_user
  end


  def authorized
    redirect_to login_path unless logged_in?
  end


end

20_rails_auth/lastam/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      redirect_to login_path
    end
  end

  def destroy
  
    session.delete(:user_id)
    redirect_to login_path
  end

end

20_rails_auth/lastam/app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index



    # I can look in sessions
    # I can find my user_id
    # I can find my user using user_id
    # I can then find my songs using my user
    # and then show songs

    if logged_in?
      @songs = current_user.songs
    else
      @songs = Song.all
    end
  end

  def show
    @song = Song.find(params[:id])
  end

  def new
    @song = Song.new
  end


  def create
    @song = Song.new(song_params)
    if @song.save
      redirect_to @song
    else
      flash[:errors] = @song.erros.full_messages
      redirect_to new_song_path
    end
  end

  def edit
    @song = Song.find(params[:id])
  end


  private
    def song_params
      params.require(:song).permit(:title)
    end
end

20_rails_auth/lastam/app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      redirect_to new_user_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

20_rails_auth/lastam/app/helpers/songs_helper.rb
module SongsHelper
end

20_rails_auth/lastam/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lastam</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>

    <% if logged_in? %>
      <%= button_to "Logout", sessions_path, method: :delete, class: "btn btn-danger" %>
    <% else %>
      <%= link_to "Login", login_path %>
    <% end %>
  </body>
</html>

20_rails_auth/lastam/app/views/songs/_form.html.erb
<div class="row">
  <div class="col-5" style="margin-top: 25px">
    <%= form_for @song do |f| %>
      <div class="form-group">
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit "Create Song", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

20_rails_auth/lastam/app/views/songs/edit.html.erb
<%= render 'form' %>

20_rails_auth/lastam/app/views/songs/index.html.erb
<div class="main">
  <ul class="list-group">
    <% @songs.each do |s| %>
      <li class="list-group-item"><%= s.title %></li>
    <% end %>
  </ul>
</div>

20_rails_auth/lastam/app/views/songs/new.html.erb
<%= render 'form' %>

20_rails_auth/lastam/app/views/songs/show.html.erb
<p><%= @song.title %></p>